
development:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_prod
  pool: 5
  timeout: 5000